<a href="https://colab.research.google.com/github/NasTiaFox30/ColabProjects/blob/master/NumPy_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**🧮 NumPy Library**

##**Ćwiczenia do wykonania**

In [2]:
import numpy as np

###**Tworzenie tablic**

**Ćwiczenie 1.** Utwórz tablicę jednowymiarową (1D) z pięcioma elementami używając funkcji np.array:

In [4]:
tablica_1d = np.arange(5)
print(tablica_1d)

[0 1 2 3 4]


**Ćwiczenie 2.** Utwórz tablicę dwuwymiarową (2D) z trzema wierszami i czterema kolumnami, używając funkcji np.array:

In [5]:
tablica_2d = np.random.random((3, 4))
print(tablica_2d)

[[0.22350913 0.28250888 0.07738202 0.60232441]
 [0.49334779 0.79934124 0.67314748 0.80518441]
 [0.33963313 0.35128983 0.63512654 0.34942976]]


**Ćwiczenie 3.** Utwórz tablicę trójwymiarową (3D) z dwoma "warstwami", trzema wierszami i czterema kolumnami, używając funkcji np.array:

In [6]:
tablica_3d = np.zeros((2, 3, 4))
print(tablica_3d)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


**Ćwiczenie 4.** Utwórz tablicę o wymiarach 2x3 wypełnioną zerami, używając funkcji np.zeros:

In [7]:
tablica_zer = np.zeros((2, 3))
print(tablica_zer)

[[0. 0. 0.]
 [0. 0. 0.]]


**Ćwiczenie 5.** Utwórz tablicę o wymiarach 3x4 wypełnioną jedynkami, używając funkcji np.ones:

In [8]:
tablica_jedynek = np.ones((3, 4))
print(tablica_jedynek)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Ćwiczenie 6.** Utwórz tablicę jednowymiarową z liczbami od 0 do 20, używając funkcji np.arange:

In [9]:
tablica_arange = np.arange(21)
print(tablica_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


**Ćwiczenie 7.** Utwórz tablicę jednowymiarową z 10 równo rozmieszczonymi liczbami między 0 a 1, używając funkcji np.linspace:

In [10]:
tablica_linspace = np.linspace(0, 1, 10)
print(tablica_linspace)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


###**Właściwości tablic**

**Ćwiczenie 8.** Korzystając z tablic utworzonych w ćwiczeniu 1, sprawdź ich kształt, wymiar, rozmiar i typ danych (.shape, .ndim, .size, .dtype). Powtórz powyższe operacje dla tablic "tablica_2d" oraz "tablica_3d":

In [11]:
print("Kształt tablica_1d:", tablica_1d.shape, tablica_2d.shape, tablica_3d.shape)
print()
print("Wymiar tablica_1d:", tablica_1d, tablica_2d, tablica_3d)
print()
print("Rozmiar tablica_1d:", len(tablica_1d), len(tablica_2d), len(tablica_3d))
print()
print("Typ danych tablica_1d:", tablica_1d, tablica_2d, tablica_3d)

Kształt tablica_1d: (5,) (3, 4) (2, 3, 4)

Wymiar tablica_1d: [0 1 2 3 4] [[0.22350913 0.28250888 0.07738202 0.60232441]
 [0.49334779 0.79934124 0.67314748 0.80518441]
 [0.33963313 0.35128983 0.63512654 0.34942976]] [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

Rozmiar tablica_1d: 5 3 2

Typ danych tablica_1d: [0 1 2 3 4] [[0.22350913 0.28250888 0.07738202 0.60232441]
 [0.49334779 0.79934124 0.67314748 0.80518441]
 [0.33963313 0.35128983 0.63512654 0.34942976]] [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


###**Indeksowanie i wycinanie tablic**

**Ćwiczenie 9.** Wybierz trzeci element tablicy "tablica_1d":

In [12]:
trzeci_element = tablica_1d[2]
print(trzeci_element)

2


**Ćwiczenie 10.** Wybierz drugi wiersz z tablicy tablica_2d:

In [13]:
drugi_wiersz = tablica_2d[1]
print(drugi_wiersz)

[0.49334779 0.79934124 0.67314748 0.80518441]


**Ćwiczenie 11.** Wybierz element na pozycji (2, 3) w tablicy "tablica_2d":

In [14]:
element_2_3 = tablica_2d[2,3]
print(element_2_3)

0.34942976345814314


**Ćwiczenie 12.** Wyciągnij wszystkie elementy z drugiej kolumny tablicy "tablica_2d":

In [15]:
druga_kolumna = tablica_2d[:,1]
print(druga_kolumna)

[0.28250888 0.79934124 0.35128983]


**Ćwiczenie 13.** Wyciągnij fragment tablicy tablica_2d (wiersze 1-2, kolumny 1-3):

In [16]:
fragment = tablica_2d[0:2,0:3]
print(fragment)

[[0.22350913 0.28250888 0.07738202]
 [0.49334779 0.79934124 0.67314748]]


###**Zmiana kształtu tablic**

**Ćwiczenie 14.** Zmień kształt tablicy "tablica_1d" na 5x1, używając funkcji **reshape**:

In [17]:
tablica_1d_reshape = np.reshape(tablica_1d, (5, 1))
print(tablica_1d_reshape)

[[0]
 [1]
 [2]
 [3]
 [4]]


**Ćwiczenie 15.** Spłaszcz tablicę "tablica_2d" do jednowymiarowej, używając funkcji **flatten**:

In [18]:
tablica_2d_flatten = tablica_2d.flatten()
print(tablica_2d_flatten)

[0.22350913 0.28250888 0.07738202 0.60232441 0.49334779 0.79934124
 0.67314748 0.80518441 0.33963313 0.35128983 0.63512654 0.34942976]


**Ćwiczenie 16.** Spłaszcz tablicę "tablica_2d" do jednowymiarowej, używając funkcji **ravel**:

In [19]:
tablica_2d_ravel = np.ravel(tablica_2d)
print(tablica_2d_ravel)

[0.22350913 0.28250888 0.07738202 0.60232441 0.49334779 0.79934124
 0.67314748 0.80518441 0.33963313 0.35128983 0.63512654 0.34942976]


###**Operacje na tablicach**

In [20]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

**Ćwiczenie 17.** Operacje na tablicach

* Dodaj dwie tablice A i B
* Odejmij tablicę B od tablicy A
* Pomnóż tablice A i B
* Podziel tablicę A przez tablicę B

In [23]:
wynik_dodawanie = A+B
print(wynik_dodawanie)

wynik_odejmowanie = A-B
print(wynik_odejmowanie)

wynik_mnozenie = A*B
print(wynik_mnozenie)

wynik_dzielenie = A/B
print(wynik_dzielenie)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
